### ISSUE TITLE
"Subscripts out of bound" error while running saturation test

### ISSUE THREAD

**Issue by wnsplim** [duchene/phylomad#10]
Hi, I'm trying to run saturation test for mitochondrial 16S rRNA gene partial sequence with total 291 positions and 300 sequences. 
When I try to run saturation test (I tried almost all available options) it keeps returning Error: Subscript Out of Bounds.
When I add multicore option to analysis, I get another error message: Error: attempt to set 'rownames' on an object with no dimensions.
What could be causing the problem? I can't really find any errors in my fasta file, and saturation test for other fasta files (produced in same way as 16s) worked all fine.

Additional question: When running saturation test with 1st+2nd versus 3rd codon positions, how does PhyloMAd locate the initiation site of translation? When I ran saturation test with CO1 gene partial sequence I got pretty sensible results (1+2 codon positions with low risk and 3rd codon position with high risk), but when visually inspected foremost part of the alignment varied pretty much from sequence to sequence. 

Thanks in advance.

**Comment by wnsplim** [comment]
by the way I'm running PhyloMAd on windows 10 environment

**Comment by duchene** [comment]
Hi Wonseop,

Do you get a message before the 'subscript out of bounds' indicating that <10% of the sites have an excess missing data, or similar? The error you are referring to usually happens in cases with excessive amounts of missing data per alignment column, i.e. when every alignment column only has a small portion of data and is mostly gaps.

Is that the case in your data? If so, I would advise testing on a highly complete subset of the data (e.g., a few taxa). Also, PhyloMAd has an option to "test complete data set", which I hope you can use. Unfortunately PhyloMAd is not currently working that well in Windows machines, so if you have the chance to use a mac machine that might help too.

Let me know if any of these options work, and I will leave the issue open for the time being.

Cheers,

David

**Comment by wnsplim** [comment]
Thank you for your quick response. Well, I tried both options ("Remove sites with missing data" and "Test complete data set ") and it didn't solve the problem. Also I didn't get any error messages concerning excess missing data, and amount of missing data of alignment is about 1.5%, which I believe is of little concern. However after some trial and errors I found that errors don't occur when I randomly remove sequences to reduce size of the alignment (from 300 sequences to about 250, regardless of completeness of an alignment). I have no idea why this happens and maybe I should try running it on macOS someday. 

P.S. I'm pretty new to field of phylogenetics, so I'm not very used to how all sorts of programs and algorithms work, so... any brief hints or comments about second question will be highly appreciated. Thanks again.

**Comment by duchene** [comment]
There is a chance that you have a few sequences in your alignment that are being problematic, possibly due to missing data, or equivalently to an excess of ambiguity characters (e.g., R, Y, W, etc.). Perhaps in your random tests you are removing some of those poorer-quality sequences?

Regarding codon position, it is important to verify that the sequences are in the correct reading frame. I often do this by using alignment software that is coding-region aware, such as [MACSE](https://www.agap-ge2pop.org/macse/). At least a brief check of your alignments "by eye" is also important, and if some sequences do not seem intuitively aligned then they are probably not providing any reliable signal, and must be excluded. Feel free to write to me if you would like any other tips/support, and for the time being I will close this issue.
